// Auto-generated Levels Enum
// Generated by SceneEnumGenerator
public enum Levels
{
    Title,
    Level1,
    Level2,
    Level3,
    Level4,
    Level5,
    Level6,
    Loading,
    WorkShop,
    Test,
}
