// Auto-generated Levels Enum
// Generated by levelsEnumGenerator
[System.Serializable]
public enum Levels
{
    Title,
    Tutorial,
    Level2,
    Level3,
    Level4,
    Level5,
    Level6,
    Loading,
    WorkShop,
    Settings,
}
